services:
    notify:
        class: Yoeunes\Notify\NotifyManager
        arguments:
            - null

    notify.twig_extension:
        class: Yoeunes\Notify\Symfony\Twig\NotifyTwigExtension
        arguments:
            - '@notify'
        public: false
        tags:
            - { name: twig.extension }

    Yoeunes\Notify\NotifyManager: '@notify'
